apiVersion: v1
kind: Service
metadata:
  name: {{ include "milvus.fullname" . }}-attu
  labels:
    app: {{ include "milvus.fullname" . }}-attu
spec:
  ports:
  - port: 3000
    name: server
  clusterIP: None
  selector:
    app: {{ include "milvus.fullname" . }}-attu