apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "milvus.fullname" . }}-attu
  labels:
    {{- include "milvus.labels" . | nindent 4 }}
spec:
  serviceName: "{{ include "milvus.fullname" . }}-attu"
  selector:
    matchLabels:
      app: {{ include "milvus.fullname" . }}-attu
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "milvus.fullname" . }}-attu
    spec:
      containers:
        - name: attu
          image: zilliz/attu:latest
          env:
            - name: MILVUS_URL
              value: '{{ include "milvus.fullname" . }}proxy:19530'
          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
            requests:
              cpu: "0.5"
              memory: "4Gi"
          lifecycle:
          ports:
            - containerPort: 3000
              name: server