apiVersion: v1
kind: Service
metadata:
  name: {{ include "milvus.fullname" . }}-datacoord
  labels:
    app: {{ include "milvus.fullname" . }}-datacoord
spec:
  ports:
  - port: 13333
    name: server
  clusterIP: None
  selector:
    app: {{ include "milvus.fullname" . }}-datacoord