apiVersion: v1
kind: Service
metadata:
  name: {{ include "milvus.fullname" . }}-datanode
  labels:
    app: {{ include "milvus.fullname" . }}-datanode
spec:
  ports:
  - port: 21124
    name: server
  clusterIP: None
  selector:
    app: {{ include "milvus.fullname" . }}-datanode