apiVersion: v1
kind: Service
metadata:
  name: {{ include "milvus.fullname" . }}-etcd
  labels:
    app: {{ include "milvus.fullname" . }}-etcd
spec:
  ports:
  - port: 2379
    name: etcd
  clusterIP: None
  selector:
    app: {{ include "milvus.fullname" . }}-etcd