apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "milvus.fullname" . }}-indexcoord
  labels:
    app: {{ include "milvus.fullname" . }}-indexcoord
spec:
  serviceName: "{{ include "milvus.fullname" . }}-indexcoord"
  selector:
    matchLabels:
      app: {{ include "milvus.fullname" . }}-indexcoord
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "milvus.fullname" . }}-indexcoord
    spec:
      containers:
        - name: indexcoord
          image: milvusdb/milvus:v2.2.3
          command: ["milvus", "run", "indexcoord"]
          env:
            - name: ETCD_ENDPOINTS
              value: '{{ include "milvus.fullname" . }}-etcd:2379'
            - name: MINIO_ADDRESS
              value: '{{ include "milvus.fullname" . }}-minio:9000'
            - name: PULSAR_ADDRESS
              value: 'pulsar://{{ include "milvus.fullname" . }}-pulsar:6650'
            - name: INDEX_COORD_ADDRESS
              value: '{{ include "milvus.fullname" . }}-indexcoord:31000'
            
          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
            requests:
              cpu: "0.5"
              memory: "4Gi"
          lifecycle:
          ports:
            - containerPort: 31000
              name: server