apiVersion: v1
kind: Service
metadata:
  name: {{ include "milvus.fullname" . }}-indexcoord
  labels:
    app: {{ include "milvus.fullname" . }}-indexcoord
spec:
  ports:
  - port: 31000
    name: server
  clusterIP: None
  selector:
    app: {{ include "milvus.fullname" . }}-indexcoord