{{ if eq .Values.platform "openshift" }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "milvus.fullname" . }}-minio
spec:
  subdomain: ''
  to:
    kind: Service
    name: {{ include "milvus.fullname" . }}-minio
    weight: 100
  port:
    targetPort: 9001
  wildcardPolicy: None
{{ end }}