apiVersion: v1
kind: Service
metadata:
  name: {{ include "milvus.fullname" . }}-proxy
  labels:
    app: {{ include "milvus.fullname" . }}-proxy
spec:
  ports:
  - port: 19530
    name: server
  - port: 9091
    name: proxy
  clusterIP: None
  selector:
    app: {{ include "milvus.fullname" . }}-proxy