apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "milvus.fullname" . }}-proxy
  labels:
    app: {{ include "milvus.fullname" . }}-proxy
spec:
  serviceName: "{{ include "milvus.fullname" . }}-proxy"
  selector:
    matchLabels:
      app: {{ include "milvus.fullname" . }}-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "milvus.fullname" . }}-proxy
    spec:
      containers:
        - name: proxy
          image: milvusdb/milvus:v2.2.3
          command: ["milvus", "run", "proxy"]
          env:
            - name: ETCD_ENDPOINTS
              value: '{{ include "milvus.fullname" . }}-etcd:2379'
            - name: MINIO_ADDRESS
              value: '{{ include "milvus.fullname" . }}-minio:9000'
            - name: PULSAR_ADDRESS
              value: '{{ include "milvus.fullname" . }}-pulsar://pulsar:6650'
          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
            requests:
              cpu: "0.5"
              memory: "4Gi"
          lifecycle:
          ports:
            - containerPort: 19530
              name: server
            - containerPort: 9091
              name: proxy  