apiVersion: v1
kind: Service
metadata:
  name: {{ include "milvus.fullname" . }}-pulsar
  labels:
    app: {{ include "milvus.fullname" . }}-pulsar
spec:
  ports:
  - port: 6650
    name: pulsar
  clusterIP: None
  selector:
    app: {{ include "milvus.fullname" . }}-pulsar