apiVersion: v1
kind: Service
metadata:
  name: {{ include "milvus.fullname" . }}-querynode
  labels:
    app: {{ include "milvus.fullname" . }}-querynode
spec:
  ports:
  - port: 21123
    name: server
  clusterIP: None
  selector:
    app: {{ include "milvus.fullname" . }}-querynode