apiVersion: v1
kind: Service
metadata:
  name: {{ include "milvus.fullname" . }}-querycoord
  labels:
    app: {{ include "milvus.fullname" . }}-querycoord
spec:
  ports:
  - port: 19531
    name: server
  clusterIP: None
  selector:
    app: {{ include "milvus.fullname" . }}-querycoord