apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "milvus.fullname" . }}-querycoord
  labels:
    app: {{ include "milvus.fullname" . }}-querycoord
spec:
  serviceName: "{{ include "milvus.fullname" . }}-querycoord"
  selector:
    matchLabels:
      app: {{ include "milvus.fullname" . }}-querycoord
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "milvus.fullname" . }}-querycoord
    spec:
      containers:
        - name: querycoord
          image: milvusdb/milvus:v2.2.3
          command: ["milvus", "run", "querycoord"]
          env:
            - name: ETCD_ENDPOINTS
              value: '{{ include "milvus.fullname" . }}-etcd:2379'
            - name: MINIO_ADDRESS
              value: '{{ include "milvus.fullname" . }}-minio:9000'
            - name: PULSAR_ADDRESS
              value: '{{ include "milvus.fullname" . }}-pulsar://pulsar:6650'
            - name: QUERY_COORD_ADDRESS
              value: '{{ include "milvus.fullname" . }}-querycoord:19531'
            
          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
            requests:
              cpu: "0.5"
              memory: "4Gi"
          lifecycle:
          ports:
            - containerPort: 19531
              name: server