apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "milvus.fullname" . }}-rootcoord
  labels:
    app: {{ include "milvus.fullname" . }}-rootcoord
spec:
  serviceName: "{{ include "milvus.fullname" . }}-rootcoord"
  selector:
    matchLabels:
      app: {{ include "milvus.fullname" . }}-rootcoord
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "milvus.fullname" . }}-rootcoord
    spec:
      containers:
        - name: rootcoord
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["milvus", "run", "rootcoord"]
          env:
            - name: ETCD_ENDPOINTS
              value: '{{ include "milvus.fullname" . }}-etcd:2379'
            - name: MINIO_ADDRESS
              value: '{{ include "milvus.fullname" . }}-minio:9000'
            - name: PULSAR_ADDRESS
              value: 'pulsar://{{ include "milvus.fullname" . }}-pulsar:6650'
            - name: ROOT_COORD_ADDRESS
              value: '{{ include "milvus.fullname" . }}-rootcoord:53100'
          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
            requests:
              cpu: "0.5"
              memory: "4Gi"
          lifecycle:
          ports:
            - containerPort: 53100
              name: server