apiVersion: v1
kind: Service
metadata:
  name: {{ include "milvus.fullname" . }}-rootcoord
  labels:
    app: {{ include "milvus.fullname" . }}-rootcoord
spec:
  ports:
  - port: 53100
    name: server
  clusterIP: None
  selector:
    app: {{ include "milvus.fullname" . }}-rootcoord